# CONFIG_ZMK_SLEEP=y
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=2
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Диагностика (временно): подробный лог событий по USB-serial. Убрать для боевого билда.
CONFIG_ZMK_LOG_LEVEL_DBG=y
